import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import rehypeExternalLinks from 'rehype-external-links';

import outboundGate from './integrations/outbound-gate.mjs';
export default defineConfig({
  site: 'https://www.lastminute-direct.de',
  trailingSlash: 'always',
  // Legacy-WP-URL -> Astro-Struktur. MUSS im Build stehen: Der Hetzner-nginx
  // liest weder public/.htaccess noch _redirects, daher emittiert Astro hier
  // statische Redirect-Seiten (0s meta-refresh + canonical), die nginx ausliefert.
  // Quelle: public/.htaccess (dort weiterhin fuer evtl. Apache-Faelle gepflegt).
  redirects: {
    '/stadtreisen/': '/staedtereisen/',
    '/abenteurer/': '/reisearten/',
    '/familie/': '/reisearten/',
    '/feinschmecker/': '/reisearten/',
    '/tipps-und-tricks/': '/ratgeber/',
    '/reisetipps-fuer-anfaenger/': '/ratgeber/',
    '/stadtreisen/nachhaltige-staedtereisen/': '/magazin/nachhaltige-staedtereisen/',
    '/stadtreisen/budgetfreundliche-staedtereisen/': '/magazin/budgetfreundliche-staedtereisen/',
    '/reiseziele/strandcamping/': '/magazin/strandcamping/',
    '/reiseziele/strandurlaub-und-yoga/': '/magazin/strandurlaub-und-yoga/',
    '/reiseziele/straende-in-karibik/': '/magazin/straende-in-karibik/',
    '/reiseziele/strandrestaurants/': '/magazin/strandrestaurants/',
    '/reiseziele/strandmode/': '/magazin/strandmode/',
    '/reiseziele/strandurlaub-in-asien/': '/magazin/strandurlaub-in-asien/',
    '/reiseziele/luxus-strandresorts/': '/magazin/luxus-strandresorts/',
    '/reiseziele/besten-inseln/': '/magazin/besten-inseln/',
    '/abenteurer/straende-fuer-wassersport/': '/magazin/straende-fuer-wassersport/',
    '/reiseziele/strandhopping/': '/magazin/strandhopping/',
    '/abenteurer/beachvolleyball/': '/magazin/beachvolleyball/',
    '/reiseziele/straende-nordamerikas/': '/magazin/straende-nordamerikas/',
    '/reiseziele/last-minute-strandurlaube/': '/magazin/last-minute-strandurlaube/',
    '/reiseziele/strandurlaub-wellness/': '/magazin/strandurlaub-wellness/',
    '/reiseziele/strandhochzeiten/': '/magazin/strandhochzeiten/',
    '/reiseziele/straende-fuer-schnorchler/': '/magazin/straende-fuer-schnorchler/',
    '/tipps-und-tricks/strandsicherheit/': '/magazin/strandsicherheit/',
    '/reiseziele/strandurlaube-nebensaison/': '/magazin/strandurlaube-nebensaison/',
    '/familie/strandurlaub-senioren/': '/magazin/strandurlaub-senioren/',
    '/reiseziele/romantische-strandurlaube/': '/magazin/romantische-strandurlaube/',
    '/reiseziele/nachhaltige-strandurlaube/': '/magazin/nachhaltige-strandurlaube/',
    '/familie/hundestraende/': '/magazin/hundestraende/',
    '/abenteurer/aktivurlaub-am-strand/': '/magazin/aktivurlaub-am-strand/',
    '/reiseziele/straende-europas/': '/magazin/straende-europas/',
    '/tipps-und-tricks/guenstige-strandurlaube/': '/magazin/guenstige-strandurlaube/',
    '/reiseziele/unentdeckte-straende/': '/magazin/unentdeckte-straende/',
    '/familie/strandurlaub-der-familie/': '/magazin/strandurlaub-der-familie/',
    '/stadtreisen/musik-und-konzerte/': '/magazin/musik-und-konzerte/',
    '/stadtreisen/entspannende-rueckzugsorte/': '/magazin/entspannende-rueckzugsorte/',
    '/stadtreisen/kunstfestivals-in-staedtereisen/': '/magazin/kunstfestivals-in-staedtereisen/',
    '/stadtreisen/sicherheitstipps/': '/magazin/sicherheitstipps/',
    '/stadtreisen/kulinarische-entdeckungen/': '/magazin/kulinarische-entdeckungen/',
    '/stadtreisen/drehorte-in-staedten/': '/magazin/drehorte-in-staedten/',
    '/stadtreisen/dynamischsten-staedte/': '/magazin/dynamischsten-staedte/',
    '/stadtreisen/besten-europaeischen-staedte/': '/magazin/besten-europaeischen-staedte/',
    '/stadtreisen/shopping-guide/': '/magazin/shopping-guide/',
    '/stadtreisen/historische-staedte/': '/magazin/historische-staedte/',
    '/stadtreisen/packliste-staedtereisen/': '/magazin/packliste-staedtereisen/',
    '/stadtreisen/oeffentlicher-verkehr/': '/magazin/oeffentlicher-verkehr/',
    '/stadtreisen/luxurioese-staedtereisen/': '/magazin/luxurioese-staedtereisen/',
    '/stadtreisen/solo-staedtereisen/': '/magazin/solo-staedtereisen/',
    '/stadtreisen/street-art-staedtereisen/': '/magazin/street-art-staedtereisen/',
    '/stadtreisen/guenstige-flugtipps/': '/magazin/guenstige-flugtipps/',
    '/stadtreisen/architektonische-wunder/': '/magazin/architektonische-wunder/',
    '/stadtreisen/kultur-pur/': '/magazin/kultur-pur/',
    '/stadtreisen/besten-jahreszeiten-staedtereisen/': '/magazin/besten-jahreszeiten-staedtereisen/',
    '/stadtreisen/geheimtipps-staedtereisen/': '/magazin/geheimtipps-staedtereisen/',
    '/stadtreisen/staedtereisen-per-fahrrad/': '/magazin/staedtereisen-per-fahrrad/',
    '/stadtreisen/staedtereisen-mit-kindern/': '/magazin/staedtereisen-mit-kindern/',
    '/stadtreisen/staedtereisen-fuer-senioren/': '/magazin/staedtereisen-fuer-senioren/',
    '/stadtreisen/staedtereisen-yoga-kombination/': '/magazin/staedtereisen-yoga-kombination/',
    '/stadtreisen/virtuelle-staedtereisen/': '/magazin/virtuelle-staedtereisen/',
    '/stadtreisen/innovative-unterkuenfte/': '/magazin/innovative-unterkuenfte/',
    '/stadtreisen/nachtleben-entertainment/': '/magazin/nachtleben-entertainment/',
    '/stadtreisen/wochenend-staedtereisen/': '/magazin/wochenend-staedtereisen/',
    '/tipps-und-tricks/last-minute-schnaeppchen/': '/magazin/last-minute-schnaeppchen/',
    '/reisetipps-fuer-anfaenger/last-minute-schnaeppchenpreis/': '/magazin/last-minute-schnaeppchenpreis/',
    '/reisetipps-fuer-anfaenger/lohnt-sich-last-minute/': '/magazin/lohnt-sich-last-minute/',
    '/reiseziele/urlaubsziele-familie/': '/magazin/urlaubsziele-familie/',
    '/reiseziele/strandurlaube-alleinreisende/': '/magazin/strandurlaube-alleinreisende/',
    '/reiseziele/strandurlaub-wohnmobil/': '/magazin/strandurlaub-wohnmobil/',
    '/reiseziele/all-inclusive-strandresorts/': '/magazin/all-inclusive-strandresorts/',
    '/abenteurer/lohnt-sich-last-minute/': '/magazin/lohnt-sich-last-minute/',
    '/lohnt-sich-last-minute-urlaub/': '/magazin/lohnt-sich-last-minute/',
    '/staedtereisen-mit-kindern-eine-familienanleitung/': '/magazin/staedtereisen-mit-kindern/',
    '/solo-staedtereisen-ein-leitfaden/': '/magazin/solo-staedtereisen/',
  },
  integrations: [outboundGate(), sitemap()],
  markdown: {
    // Externe Links in Artikeln automatisch absichern (rel + target).
    // Interne /magazin/-Links bleiben unberuehrt.
    rehypePlugins: [
      [rehypeExternalLinks, { target: '_blank', rel: ['nofollow', 'noopener'] }],
    ],
  },
  vite: {
    plugins: [tailwindcss()],
  },
});
